name: CI-CD

# on:
#   push:
#     branches: ["main"]
#   workflow_dispatch:

on:
  push:
    paths:
      # - './outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02/k8s/start.text'
      - './.github/workflows/curso_081.yaml'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout do repositório
    #   uses: actions/checkout@v4.1.1
    - name: Checkout do repositório
      uses: actions/checkout@v4.1.1
      with:
        path: ./outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}      
    # - name: Build and push Docker images
    #   uses: docker/build-push-action@v5.0.0
    #   with:
    #     context: ./outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02/kube-news/src
    #     file: ./outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02/kube-news/src/Dockerfile
    #     push: true
    #     tags: |
    #       pedroheeger/curso081_kube-news:${{github.run_number}}
    #       pedroheeger/curso081_kube-news:latest



      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4.1.1
      with:
        path: ./outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02
    - name: Configuração da credencial da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: us-east-1
    # - name: Configurar o KubeConfig
    #   run: aws eks update-kubeconfig --name curso081Cluster --region us-east-1
    # - name: Deploy to Kubernetes cluster
    #   uses: Azure/k8s-deploy@v4.9
    #   with:
    #     manifests: 
    #       ./outros/fabricio_veronez/devops/curso_081/imersao-devops-cloud-02/kube-news/k8s/deployment3.yaml
    #     images:
    #       pedroheeger/curso081_kube-news:${{github.run_number}}